"""Generate the GitHub Copilot instruction surfaces.

AGENTS.md is the single source of truth for the resident-interviewer persona.
GitHub.com Copilot does not consume ``AGENTS.md`` on every surface, so the
repo-wide instruction file still receives the full persona region (between the
``<!-- BEGIN:persona -->`` / ``<!-- END:persona -->`` markers):

  - `.github/copilot-instructions.md`: repo-wide Copilot instructions.
  - `.github/agents/interviewer.agent.md`: a thin VS Code adapter with no
    direct edit tool. VS Code applies root ``AGENTS.md`` natively, so repeating
    the full persona in this file would create a second source of truth.
  - `.github/prompts/*.prompt.md`: small command routers generated from one
    paradigm table.

The workspace disables automatic use of ``copilot-instructions.md`` in VS
Code, preventing the full persona from being applied beside root
``AGENTS.md``. GitHub.com still consumes the generated file.

Both outputs are deterministic: no timestamps, stable ordering, trailing
newline. Edit the persona in AGENTS.md, then run `just gen-agents`;
`scripts/check_agent_instructions.py` guards against drift.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AGENTS = ROOT / "AGENTS.md"
COPILOT_INSTRUCTIONS = ROOT / ".github" / "copilot-instructions.md"
INTERVIEWER_AGENT = ROOT / ".github" / "agents" / "interviewer.agent.md"
PROMPT_DIR = ROOT / ".github" / "prompts"

BEGIN_MARKER = "<!-- BEGIN:persona -->"
END_MARKER = "<!-- END:persona -->"

COPILOT_HEADER = (
    "<!-- GENERATED from AGENTS.md persona region "
    ": edit there, then run: just gen-agents -->"
)
AGENT_HEADER = (
    "<!-- GENERATED by scripts/gen_agent_instructions.py "
    ": behavioral authority: AGENTS.md -->"
)
PROMPT_HEADER = "<!-- GENERATED by scripts/gen_agent_instructions.py -->"

# One orientation sentence so a cold Copilot session knows what the repo is
# before it reads the persona.
ORIENTATION = (
    "This repository is a public, company-neutral technical-interview study "
    "packet whose purpose is a repeatable practice day that trains confident, "
    "non-panicked reasoning-out-loud under observation."
)

# Kept free of any colon-space or trailing hash so it stays a valid YAML plain
# scalar. Written to make Copilot surface the agent for interview practice asks.
AGENT_DESCRIPTION = (
    "Candidate-preserving resident interviewer for editor-first technical-interview "
    "practice using comments, code, tests, and the REPL."
)

# Current VS Code built-in tool identifiers. Edit tools are intentionally
# absent. Terminal execution is still broad, so candidate ownership is a
# behavioral contract enforced by AGENTS.md, not an OS-level capability wall.
AGENT_TOOLS = (
    "read/readFile",
    "execute/runInTerminal",
    "execute/getTerminalOutput",
)

AGENT_BODY = """Read the resident-interviewer contract in root `AGENTS.md`.
Run only documented `just` recipes and trust their output. A slash command
already selects the mode. Only `just practice-start` may seed a workspace.
After it returns, never change candidate source, tests, comments, or the gate.
Relay the command's `NEXT:` line and stop. For `/continue`, run
`just practice-next`, relay its `STATE:` and `NEXT:` lines, and stop.

Terminal access is broad, so the missing edit tool is not a security boundary.
The candidate-ownership rule is mandatory."""

PROMPT_SPECS: dict[str, tuple[str, str]] = {
    "reacto": ("Start a REACTO editor rep", "REACTO"),
    "clarp": ("Start a CLARP editor rep", "CLARP"),
    "umpire": ("Start a UMPIRE editor rep", "UMPIRE"),
    "comments": ("Start an editor rep with plain comments", "plain comments"),
}


class PersonaMarkerError(RuntimeError):
    """Raised when the AGENTS.md persona markers are missing or duplicated."""


def extract_persona(text: str) -> str:
    """Return the persona body between the markers, verbatim.

    Leading and trailing blank lines are trimmed so the output stays stable
    regardless of spacing around the markers. Interior text is untouched.
    """
    lines = text.splitlines()
    begins = [i for i, line in enumerate(lines) if line.strip() == BEGIN_MARKER]
    ends = [i for i, line in enumerate(lines) if line.strip() == END_MARKER]

    if len(begins) != 1 or len(ends) != 1:
        raise PersonaMarkerError(
            f"expected exactly one {BEGIN_MARKER} and one {END_MARKER} in "
            f"{AGENTS.relative_to(ROOT).as_posix()}; found "
            f"{len(begins)} begin and {len(ends)} end marker(s)"
        )
    begin, end = begins[0], ends[0]
    if begin >= end:
        raise PersonaMarkerError(
            f"{BEGIN_MARKER} must appear before {END_MARKER} in "
            f"{AGENTS.relative_to(ROOT).as_posix()}"
        )

    body = lines[begin + 1 : end]
    while body and not body[0].strip():
        body.pop(0)
    while body and not body[-1].strip():
        body.pop()
    if not body:
        raise PersonaMarkerError("persona region is empty")
    return "\n".join(body)


def render_copilot_instructions(persona: str) -> str:
    return "\n".join([COPILOT_HEADER, "", ORIENTATION, "", persona]) + "\n"


def render_interviewer_agent() -> str:
    frontmatter = [
        "---",
        "name: Interviewer",
        f"description: {AGENT_DESCRIPTION}",
        "target: vscode",
        "tools:",
        *(f"  - {tool}" for tool in AGENT_TOOLS),
        "---",
    ]
    return "\n".join([*frontmatter, "", AGENT_HEADER, "", AGENT_BODY]) + "\n"


def render_start_prompt(name: str, description: str, label: str) -> str:
    return f"""---
name: {name}
description: {description}
argument-hint: "[topic problem]"
agent: 'Interviewer'
---

{PROMPT_HEADER}

Start a {label} editor rep. Run `just practice-start {name}`. Append arguments only when
the invocation contains exactly two lowercase identifiers. Run nothing else.
On success, relay the command's `STATE:` and `NEXT:` lines, then stop. Only
the recipe may seed files. Never edit the candidate workspace.
"""


def render_continue_prompt() -> str:
    return f"""---
name: continue
description: Show the current rep state and one next action
agent: 'Interviewer'
---

{PROMPT_HEADER}

Run `just practice-next`. If it fails, report the error. Otherwise relay its
`STATE:` and `NEXT:` lines, then stop. Never edit the candidate workspace or
invent session state.
"""


def generated_files() -> dict[Path, str]:
    """Map each output path to its deterministic content."""
    persona = extract_persona(AGENTS.read_text())
    files = {
        COPILOT_INSTRUCTIONS: render_copilot_instructions(persona),
        INTERVIEWER_AGENT: render_interviewer_agent(),
    }
    files.update(
        {
            PROMPT_DIR / f"{name}.prompt.md": render_start_prompt(
                name, description, label
            )
            for name, (description, label) in PROMPT_SPECS.items()
        }
    )
    files[PROMPT_DIR / "continue.prompt.md"] = render_continue_prompt()
    return files


def main() -> int:
    try:
        files = generated_files()
    except PersonaMarkerError as exc:
        print(f"gen_agent_instructions: {exc}", file=sys.stderr)
        return 1

    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    rels = ", ".join(sorted(path.relative_to(ROOT).as_posix() for path in files))
    print(f"Generated Copilot instruction surfaces from AGENTS.md: {rels}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
